// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmoT32P3d6O2jFQ0sJ9GfYWsmwaQk1mJE',
    appId: '1:614795150824:web:e4dee7892550293452d05d',
    messagingSenderId: '614795150824',
    projectId: 'hello-neighbor-a491f',
    authDomain: 'hello-neighbor-a491f.firebaseapp.com',
    storageBucket: 'hello-neighbor-a491f.appspot.com',
    measurementId: 'G-4VMX0502N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCHehZUcyrSm8rtMkqaik5-vJs9hqOfM',
    appId: '1:614795150824:android:46d4ebe579e0438952d05d',
    messagingSenderId: '614795150824',
    projectId: 'hello-neighbor-a491f',
    storageBucket: 'hello-neighbor-a491f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWKRVOSa-EyIw08We82sRsT3fESp-9GXE',
    appId: '1:614795150824:ios:3d832e904c52848852d05d',
    messagingSenderId: '614795150824',
    projectId: 'hello-neighbor-a491f',
    storageBucket: 'hello-neighbor-a491f.appspot.com',
    iosBundleId: 'com.example.helloneighbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWKRVOSa-EyIw08We82sRsT3fESp-9GXE',
    appId: '1:614795150824:ios:a0e34555d2f8228a52d05d',
    messagingSenderId: '614795150824',
    projectId: 'hello-neighbor-a491f',
    storageBucket: 'hello-neighbor-a491f.appspot.com',
    iosBundleId: 'com.example.helloneighbor.RunnerTests',
  );
}
